### ISSUE TITLE
Gifv files from imgur being labeled as gif

### ISSUE THREAD

**Issue by odsod** [Oted/messapp-backend#2]
Gifv seems to be Imgur's own invention, in reality being mp4 / webm clips.

http://imgur.com/blog/2014/10/09/introducing-gifv

Either replace gifv with gif (seems to work, at least for some files) or create a new gifv content type.

**Comment by Oted** [comment]
.gifv extension is now classed as a video type, together with mp4, ogg and .webm

**Comment by odsod** [comment]
The frontend will still need to treat gifv items differently from other video items, since the link does not lead to a video file embeddable in a `<video>` tag. (Instead, the link leads to an Imgur page, which in turn embeds the actual video clip, which seems to be an mp4 file most of the time.)

To support gifv in the frontend, we must detect that it is a gifv, and give the url special treatment (possibly embedding an iframe with the Imgur page inside).

The frontend can do a `/.gifv$/` regex to detect this, but we could also create a `gifv` type in the backend.

**Comment by Oted** [comment]
kden... gifv now added as separate type :pppPPP
